<?php

namespace Neoan3\Component\Migrate;

use PHPUnit\Framework\TestCase;

/**
 * Class PostTest
 * Generated by neoan3-cli
 * @package Neoan3\Component\Migrate
 */
class MigrateTest extends TestCase
{
    private MigrateController $instance;
    function setUp(): void
    {
        $this->instance = new MigrateController();
    }
        /**
     *  Route output shall have no errors
     */
    public function testInit()
    {
        /**
         * Using models?
         * You can use the same mock-helpers as the models themselves.
         *
         * e.g. to mock a ::find call
         * $mockDb = new \Neoan3\Provider\MySql\MockDatabaseWrapper([]);
         * $mockDb->mockFind('component');
         * // don't forget to register your mock provider(s in the right order)
         * $this->instance->registerProvider($mockDb);
         *
         */
        $this->expectOutputRegex('/^<!doctype html>/');
        $this->instance->init();
    }

    function testPostMigrate()
    {
        $response = $this->instance->postMigrate(['name'=>'notModel']);
        $this->assertIsArray($response);
        $this->assertSame(['name'=>'notModel'], $response);
    }

}
