<?php

/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Frame\Demo;

/**
 * Class Endpoint
 * @package Neoan3\Components
 */

class Endpoint extends Demo{

    function getEndpoint($userType='self', $id=null, $params=[]): array
    {
        return array_merge([
            'type' => $userType,
            'id' => $id,
        ],$params);
    }
}
