<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;


class Transformer
{
    private static $structure = [];
    function init($neosn3transformStructure)
    {
        $this->uni()->output();
    }

}
