<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;

use Neoan3\Apps\Db;

class UserModel extends IndexModel
{
    static function byId($id)
    {
        
    }

    static function find($condition)
    {
        
    }
    static function get($id){
        $structure = parent::getMigrateStructure('user');
        $transformer = UserTransformer::validate();
        // transformer-translations?
        $translatedTransformer = [];
        foreach ($transformer as $tableOrColumn => $values){
            if(isset($values['translate'])){
                $translatedTransformer[$values['translate']] = $values;
                $translatedTransformer[$values['translate']]['translate'] = $tableOrColumn;
            } else {
                $translatedTransformer[$tableOrColumn] = $values;
            }
        }
        $includeDeleted = false;
        $queries = ['user'=>[]];
        $model = 'user';
        foreach ($structure as $tableOrColumn => $definition){
            reset($definition);
            if(is_array($definition[key($definition)])){
                // is table
                if(isset($translatedTransformer[$tableOrColumn]['protection']) && $translatedTransformer[$tableOrColumn]['protection'] == 'hidden'){
                    continue;
                }
                $queries[$tableOrColumn]['as'] = isset($translatedTransformer[$tableOrColumn]['translate'])?$translatedTransformer[$tableOrColumn]['translate'] : $tableOrColumn;;
                $queries[$tableOrColumn]['where'] = [];
                if(!$includeDeleted){
                    $queries[$tableOrColumn]['where'] = ['^delete_date'];
                }
                $queries[$tableOrColumn]['depth'] = isset($translatedTransformer[$tableOrColumn]['depth'])?$translatedTransformer[$tableOrColumn]['depth'] : 'many';
                foreach ($definition as $key =>$value){
                    if($key == $model .'_id'){
                        $queries[$tableOrColumn]['where'][$key] = '$'.$id;
                    }
                    // default
                    $queries[$tableOrColumn]['select'][$key] = $tableOrColumn.'.'.$key;
                    if(isset($translatedTransformer[$tableOrColumn])){
                        // onRead?
                        if(isset($translatedTransformer[$tableOrColumn]['on_read']) && isset($translatedTransformer[$tableOrColumn]['on_read'][$key])){
                            $queries[$tableOrColumn]['select'][$key] = $translatedTransformer[$tableOrColumn]['on_read'][$key]($key);
                        }
                    }
                }
            } else {
                // is key of main
                $queries[$model]['depth'] = 'main';
                $queries[$model]['as'] = $model;
                if($tableOrColumn == 'id'){
                    $queries[$model]['where'][$tableOrColumn] = '$'.$id;
                }
                // default
                $queries[$model]['select'][$tableOrColumn] = $model.'.'.$tableOrColumn;
                if(isset($translatedTransformer[$tableOrColumn])){
                    // is hidden/protected?
                    if(isset($translatedTransformer[$tableOrColumn]['protection'])){
                        // do nothing for now
                        unset($queries[$model]['select'][$tableOrColumn]);
                    } else {
                        // onRead?
                        if(isset($translatedTransformer[$tableOrColumn]['on_read'])){
                            $queries[$model]['select'][$tableOrColumn] = $translatedTransformer[$tableOrColumn]['on_read']($tableOrColumn);
                        }
                        // translate?
                        if(isset($translatedTransformer[$tableOrColumn]['translate'])){
                            $queries[$model]['select'][$tableOrColumn] .= ':' . $translatedTransformer[$tableOrColumn]['translate'];
                        }
                    }
                }
            }
        }
        foreach ($queries as $i =>$query){
            $queries[$i]['select'] = implode(' ',array_values($queries[$i]['select']));
        }
        $entity = [];

        foreach ($queries as $table => $query){
            try{
                switch ($query['depth']){
                    case 'main': $entity = IndexModel::first(Db::easy($query['select'],$query['where'])); break;
                    case 'one': $entity[$query['as']] = IndexModel::first(Db::easy($query['select'],$query['where'])); break;
                    case 'many': $entity[$query['as']] = Db::easy($query['select'],$query['where']); break;
                }
            } catch (DbException $e){
                var_dump($e->getMessage());
            }
        }
        return $entity;
    }
    static function create($obj)
    {
        $transform = parent::validateAgainstTransformer($obj,userTransformer::modelStructure());
        $toDb = parent::flatten('user',$transform);
        /*foreach ($toDb as $table => $values){
            Db::$table($values);
        }*/
        var_dump($toDb);
    }
}
